<?php

namespace App\Http\Controllers\Admin;

use App\Models\Entities\MenuItem;
use App\Models\Entities\Video;
use Backpack\CRUD\app\Http\Controllers\CrudController;

use App\Http\Requests\StoreVideoRequest as StoreRequest;
use App\Http\Requests\UpdateVideoRequest as UpdateRequest;

class VideoController extends CrudController
{
    public function __construct() {
        parent::__construct();

        $this->crud->setModel(Video::class);
        $this->crud->setRoute("admin/video");
        $this->crud->setEntityNameStrings(trans('label.video'), trans('label.videos'));

        //List Columns cofiguration
        $this->crud->addColumn(['name' => 'id', 'label' => trans('label.id')]);
        $this->crud->addColumn(['name' => 'title', 'label' => trans('label.title')]);
        $this->crud->addColumn(['name' => 'menu_item', 'type'=>'select', 'label' => trans('label.menu_item'),
            'entity' => 'menuItem', 'attribute' => 'name', 'model'=> MenuItem::class]);
        $this->crud->addColumn(['name' => 'order', 'label' => trans('label.order')]);
        $this->crud->addColumn(['name' => 'created_at', 'label' => trans('label.created_at')]);

        //Form for create and update
        $this->crud->addField(['name' => 'title', 'label' => trans('label.title')]);
        $this->crud->addField(['name' => 'url', 'label' => trans('label.url')]);
        $this->crud->addField(['name' => 'menu_item_id', 'type' => 'select', 'label' => trans('label.menu_item'),
            'entity' => 'menuItem', 'attribute' => 'name', 'model' => MenuItem::class]);
        $this->crud->addField(['name' => 'visible_for', 'type' => 'select_from_array', 'label' => trans('label.visible_for'),
            'options' => ['client' => trans('label.client'), 'partner' => trans('label.partner')]]);
        $this->crud->addField(['name' => 'url_type', 'type' => 'select_from_array', 'label' => trans('label.url_type'),
            'options' => ['video' => trans('label.video'), 'link' => trans('label.link')]]);
        $this->crud->addField(['name' => 'order', 'type' => 'number', 'label' => trans('label.order')]);
        $this->crud->addField(['name' => 'description', 'type' => 'ckeditor', 'label' => trans('label.description')]);
    }

    public function index()
    {


        return parent::index(); // TODO: Change the autogenerated stub
    }

    public function store(StoreRequest $request)
    {
        return parent::storeCrud();
    }

    public function update(UpdateRequest $request)
    {
        return parent::updateCrud();
    }

}
